openapi: 3.0.0
info:
  title: 'DISHTANSYA Api'
  description: 'This is the DISHTANSYA API documentation.'
  version: 1.0.0
servers:
  -
    url: 'http://api.dishtansya.com/v1'
    description: 'Local Server'
paths:
  /register:
    post:
      tags:
        - auth-service
      summary: 'Register user into the system'
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              type: object
      responses:
        201:
          description: Success
          content:
            application/json: {  }
        400:
          description: 'Bad Request'
        401:
          description: Unauthorized
        422:
          description: 'Unprocessable Entity'
        500:
          description: 'Internal Server'
  /login:
    post:
      tags:
        - auth-service
      summary: 'Logs user into the system'
      description: 'User must be authorized to login'
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              type: object
      responses:
        201:
          description: Success
          content:
            application/json: {  }
        400:
          description: 'Bad Request'
        401:
          description: Unauthorized
        422:
          description: 'Unprocessable Entity'
        429:
          description: 'Too Many Requests'
        500:
          description: 'Internal Server'
  /logout:
    post:
      tags:
        - auth-service
      summary: 'Logs out current user'
      description: 'Logs out current logged in user session'
      operationId: logoutUser
      responses:
        201:
          description: Success
          content:
            application/json: {  }
        400:
          description: 'Bad Request'
        401:
          description: Unauthorized
        500:
          description: 'Internal Server'
      security:
        -
          bearerAuth: {  }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  -
    name: auth-service
    description: 'Auth Controller'
